// Code generated by hertz generator.

package social

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	social "w2-work4/biz/model/social"
)

// ActionRelation .
// @router /v1/relation/action [POST]
func ActionRelation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.ActionRelationRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.ActionRelationResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListFollowing .
// @router /v1/following/list [GET]
func ListFollowing(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.ListFollowingRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.SocialResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListFollower .
// @router /v1/follower/list [GET]
func ListFollower(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.ListFollowerRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.SocialResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListFriends .
// @router /v1/friends/list [GET]
func ListFriends(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.ListFriendsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.SocialResponse)

	c.JSON(consts.StatusOK, resp)
}
