// Code generated by hertz generator.

package video

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	video "w2-work4/biz/model/video"
)

// FeedVideo .
// @router /v1/video/feed/ [GET]
func FeedVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.FeedVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.FeedVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// PublishVideo .
// @router /v1/video/publish/ [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PublishVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListVideo .
// @router /v1/video/list/ [GET]
func ListVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.ListVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.ListVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// PopularVideo .
// @router /v1/video/popular/ [GET]
func PopularVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PopularVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PopularVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// SearchVideo .
// @router /v1/video/search/ [POST]
func SearchVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.SearchVideoResponse)

	c.JSON(consts.StatusOK, resp)
}
