// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	interact "w2-work4/biz/router/interact"
	social "w2-work4/biz/router/social"
	user "w2-work4/biz/router/user"
	video "w2-work4/biz/router/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	interact.Register(r)

	social.Register(r)

	video.Register(r)

	user.Register(r)
}
